### ISSUE TITLE
Support for Rtl 8723de on Solus? I will help you in any way I can. 

### ISSUE THREAD

**Issue by cata0309** [linuxerus/rtl-driver-installer#19]

**Comment by Alexander88207** [comment]
Hi @cata0309 Thanks for suggestion :)

The driver is on the way!

**Comment by cata0309** [comment]
Thank you very much!! If I am not annoying you can you tell me when it will be in the installer. Don't get me wrong please. Just asking.

**Comment by cata0309** [comment]
It is "de", not "be" right?

**Comment by Alexander88207** [comment]
both exists

**Comment by cata0309** [comment]
Thank you, I appreciate your work.

**Comment by Alexander88207** [comment]
The driver will be available in one hour in testing.

**Comment by Alexander88207** [comment]
Now in testing can you test it?

```
wget https://raw.githubusercontent.com/linuxerus/rtl-driver-installer/testing/Installer.sh
bash Installer.sh
```

**Comment by cata0309** [comment]
Give me 30 minutes, I installed Solus again and now it is upgrading all the packages

**Comment by Alexander88207** [comment]
alright

**Comment by cata0309** [comment]
What headers should I choose current or Lts ?

**Comment by Alexander88207** [comment]
current

**Comment by cata0309** [comment]
Should I choose to download the sources t
![image](https://user-images.githubusercontent.com/35623921/59061290-cb1d7000-88ab-11e9-9ea5-df9967e664e5.png)

**Comment by cata0309** [comment]
This error popped up

**Comment by Alexander88207** [comment]
can you try
`
sudo modprobe rtl8723de`

**Comment by cata0309** [comment]
Look at the modules version, shouldn't be 5.0.16-116 ? the linux-current-headers ?

**Comment by Alexander88207** [comment]
oh can you restart your pc please?

**Comment by Alexander88207** [comment]
solus still thinks you are on 4.20 but its now 5 after update

**Comment by cata0309** [comment]
Uof, I don't know how to make 5 the default one

**Comment by Alexander88207** [comment]
just restart the pc

**Comment by cata0309** [comment]
![image](https://user-images.githubusercontent.com/35623921/59061849-1edc8900-88ad-11e9-882a-d76a0015b090.png)

**Comment by Alexander88207** [comment]
sudo modprobe 8723be

**Comment by cata0309** [comment]
The modules are updated, but as shown there, there's no rtl8723de option

**Comment by cata0309** [comment]
Same result, not found

**Comment by Alexander88207** [comment]
Do you this driver installed?

**Comment by cata0309** [comment]
I didn't installed that driver, just the rtl8723de

**Comment by cata0309** [comment]
I restarted the installer and now it is building something

**Comment by Alexander88207** [comment]
Thats what i have meaned sry :D

**Comment by cata0309** [comment]
I LOVE YOU MAN !

**Comment by Alexander88207** [comment]
it worked?

**Comment by cata0309** [comment]
It worked like charm, all I had to do is restart the computer after installing the headers and restart the installer, it was building with that CC and stuff

**Comment by Alexander88207** [comment]
Do can connect to a wifi now?

**Comment by cata0309** [comment]
Yes, I respond to you from my wifi connection

**Comment by cata0309** [comment]
I am connected already

**Comment by cata0309** [comment]
I would like to write the Readme file in the future ????? I want to be a member of the stuff

**Comment by cata0309** [comment]
Or write in the Readme that the linux-current-headers must be first installed and restart the computer before starting the installer

**Comment by Alexander88207** [comment]
Normally it looks like this:

1. Updating Solus
2. Restart
3. Use my Script 

Done.

btw the linux-current-headers  gets already shipped with my script.

**Comment by cata0309** [comment]
That is the problem

**Comment by cata0309** [comment]
not updating solus

**Comment by Alexander88207** [comment]
Anyway if you have no wifi after a kernel update use "Reinstall". If you have accepted the "leave files for a kernel update question" .

**Comment by cata0309** [comment]
It should be like this:

 1.Updating Solus
 2.Install git via sudo eopkg install git (or the wget)
 3.Install build-essentials with  sudo eopkg it -c system.devel
 4.Install linux-current-headers via sudo eopkg install linux-current-headers
 5.Restart
 6.Use my Script
 

NOTE:  Accept the "leave files for a kernel update question" . If you update the kernel and have problems with it you will be able to reinstall it again

**Comment by cata0309** [comment]
The linux-current-headers must be installed and after that you restart, your script doesn't made that possible because you install the linux-current-headers and jump right to the installation after with no restart

**Comment by cata0309** [comment]
And the kernel modules are still the old ones.I hope you understand what I am saying

**Comment by cata0309** [comment]
Can I a contributor ?

**Comment by cata0309** [comment]
A member of the team I mean

**Comment by Alexander88207** [comment]
Unfortunately, it's not that simple.

I don't want to sound out of touch now, but you must have contributed a lot to it.

**Comment by cata0309** [comment]
Well, no problem, I will contribute to it. It made my day
